name: Docker Image CI

on:
  pull_request:
    branches: [ "HelloWorld3" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerile --tag my-image-name:$(date +%s)
